provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  nodetz:
    lang: node
    handler: ./nodetz
    image: ericstoekl/nodetz

  pytest1:
    lang: python
    handler: ./pytest1
    image: ericstoekl/pytest1

  gotest:
    lang: go
    handler: ./gotest
    image: ericstoekl/gotest
