provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  binarytreemaze:
    lang: go
    handler: ./binarytreemaze
    image: ericstoekl/binarytreemaze
    environment:
      write_debug: true
